import express from "express";
import connection from "./database/db.js";
import DefaultData from "./default.js";
import { configDotenv } from "dotenv";
import Router from "./routes/route.js";
import cors from "cors";
import bodyParser from "body-parser";
const app = express();
app.use(cors());
app.use(bodyParser.json({ extended: true }));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(Router);
configDotenv();
const PORT = 8000;
const url = process.env.MONGODB_URL;
connection(url);
app.listen(PORT, () => {
  console.log(`App is running at Port ${8000}`);
});
DefaultData();
